networks:
  default:
    name: dropin
    external: true

volumes:
  letsencrypt_data:
    external: true
  green_tech_images:
    external: true
  green_tech_db:
    external: true

services:
  traefik:
    image: traefik:v2.9
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true

      - --certificatesresolvers.resolver.acme.tlschallenge=true
      - --certificatesresolvers.resolver.acme.email=shohrukh.m.qurbonov@gmail.com
      - --certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://(?:www\\.)?(.+)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt_data:/letsencrypt

  backend:
    container_name: "backend"
    restart: always
    build:
      context: ../packages/server
      dockerfile: Dockerfile
      args:
        PORT: $PORT
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`server.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=https
      - traefik.http.routers.backend.tls.certresolver=resolver
      - traefik.http.services.backend.loadbalancer.server.port=${PORT}
      - traefik.http.middlewares.api.ratelimit.average=100
      - traefik.http.middlewares.api.ratelimit.period=1s
      - traefik.http.middlewares.api.ratelimit.burst=75
      - traefik.http.middlewares.api.ratelimit.sourceCriterion.requestHeaderName=X-Forwarded-For
      - traefik.http.routers.backend.middlewares=api
    environment:
      PORT: $PORT
      NODE_ENV: "production"
      DB_HOST: "database"
      DB_PORT: 5432
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      JWT_ACCESS_SECRET: $JWT_ACCESS_SECRET
      JWT_REFRESH_SECRET: $JWT_REFRESH_SECRET

    depends_on:
      - database
      - traefik
    volumes:
      - green_tech_images:/var/www/server/src/uploads

  frontend:
    container_name: "frontend"
    restart: always
    build:
      context: ../packages/web
      dockerfile: Dockerfile
      args:
        NODE_ENV: "production"
        SERVER_URL: "https://server.${DOMAIN}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls.certresolver=resolver
      - traefik.http.services.frontend.loadbalancer.server.port=80
    environment:
      NODE_ENV: "production"
      SERVER_URL: "https://server.${DOMAIN}"
    depends_on:
      - backend
      - traefik

  # -----------------------------------------------------------
  #
  # -----------------------------------------------------------
  database:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "$DB_PORT:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    volumes:
      - green_tech_db:/var/lib/postgresql/data
